version: '3.3'
services:
  dajin_triton:
    image: nvcr.io/nvidia/tensorrtserver:19.10-py3
    shm_size: '8gb'
    container_name: dajin_triton
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    ports:
      - 20407:20407
      - 20408:20408
      - 20409:20409
    volumes:
      - ./trtis_models:/trtis_models
    command: trtserver --http-port=20407 --grpc-port=20408 --metrics-port=20409 --model-store=/trtis_models
    
